# Generated by Django 4.2.3 on 2023-09-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_memberdata_memberscandata_menudata_orderdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('use', models.BooleanField()),
            ],
        ),
    ]
