# Generated by Django 4.2.3 on 2023-09-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_tabledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='checkout',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
