# Generated by Django 4.2.3 on 2023-09-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_orderdata_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderData',
        ),
    ]
