# Generated by Django 4.2.3 on 2023-09-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_orderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdata',
            name='admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
