# Generated by Django 4.2.3 on 2023-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_rename_student_id_memberdata_member_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='barcode',
            field=models.CharField(default='TABLE', max_length=15),
            preserve_default=False,
        ),
    ]
