# Generated by Django 4.2.3 on 2023-09-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_tabledata_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledata',
            name='barcode',
        ),
    ]
