# Generated by Django 4.2.3 on 2023-09-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_remove_tabledata_barcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ticketScanData',
            new_name='ticketData',
        ),
    ]
