# Generated by Django 4.2.3 on 2023-09-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_rename_ticketscandata_ticketdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdata',
            name='available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
