# Generated by Django 4.2.3 on 2023-09-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_ticketdata_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudata',
            name='soldout',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
