# Generated by Django 4.2.3 on 2023-09-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_menudata_soldout'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherOrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('checkout', models.BooleanField()),
            ],
        ),
    ]
