# Generated by Django 4.2.3 on 2023-09-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_otherorderdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otherOrderData',
        ),
        migrations.AddField(
            model_name='tabledata',
            name='message',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
