# Generated by Django 4.2.3 on 2023-09-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_delete_otherorderdata_tabledata_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='forWorkerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
