# Generated by Django 4.2.5 on 2023-09-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_forworkerdata_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabledata',
            name='ticket_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
