# Generated by Django 4.2.5 on 2023-09-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberscandata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='memberscandata',
            name='status',
        ),
        migrations.RemoveField(
            model_name='memberscandata',
            name='student_id',
        ),
        migrations.AddField(
            model_name='memberscandata',
            name='member_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
