# Generated by Django 4.2.5 on 2023-10-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_remove_memberscandata_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shiftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='memberscandata',
            name='work',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
