# Generated by Django 4.2.5 on 2023-10-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_shiftdata_memberscandata_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdata',
            name='barcode',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='barcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
