# Generated by Django 4.2.5 on 2023-10-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_alter_memberdata_barcode_alter_ticketdata_barcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='memberData',
        ),
        migrations.DeleteModel(
            name='memberScanData',
        ),
        migrations.DeleteModel(
            name='shiftData',
        ),
    ]
