# Generated by Django 4.2.5 on 2023-10-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_delete_memberdata_delete_memberscandata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='analyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
