services:
  app:
    container_name: sf-order-app
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    command: wait-for-it db:5432 -- python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  web:
    container_name: sf-order-web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
  
  db:
    container_name: sf-order-db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
