services:
  app:
    image: sf-order-app
    container_name: sf-order-app
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    command: wait-for-it db:5432 -- python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  web:
    image: sf-order-web
    container_name: sf-order-web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: sf-order-db
    container_name: sf-order-db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data

volumes:
  db-data:
    name: sf-order-db-volumes
    driver: local
